version: '3.8'
services:
  app:
    container_name: api_app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
#    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose:
      - 80
    depends_on:
      - db
    networks:
      - api-network

  db:
    image: mysql:8.0.25
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    networks:
      - api-network

volumes:
  dbdata:
    driver: local
networks:
  api-network:
    driver: bridge
